//auth
export const  LOGIN_SUCCESS = 'LOGIN_SUCCES';
export const  LOGIN_FAIL = 'LOGIN_fAIL';
export const  LOGIN_REQUEST = 'LOGIN_REQUEST';
export const  LOG_OUT = 'LOG_OUT';
export const  LOAD_PROFILE = 'LOAD_PROFILE';

//videos
export const  HOME_VIDEOS_SUCCESS = 'HOME_VIDEOS_SUCCESS';
export const  HOME_VIDEOS_FAIL = 'HOME_VIDEOS_FAIL';
export const  HOME_VIDEOS_REQUEST = 'HOME_VIDEOS_REQUEST';

//video by id
export const  SELECTED_VIDEOS_SUCCESS = 'SELECTED_VIDEOS_SUCCESS';
export const  SELECTED_VIDEOS_FAIL = 'SELECTED_VIDEOS_FAIL';
export const  SELECTED_VIDEOS_REQUEST = 'SELECTED_VIDEOS_REQUEST';


// Channel
export const  CHANNEL_DETAILS_REQUEST = 'CHANNEL_DETAILS_REQUEST';
export const  CHANNEL_DETAILS_FAIL = 'CHANNEL_DETAILS_FAIL';
export const  CHANNEL_DETAILS_SUCCESS = 'CHANNEL_DETAILS_SUCCESS';

// Comments
export const  COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const  COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL';
export const  COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';

