export const  LOGIN_SUCCESS = 'LOGIN_SUCCES'
export const  LOGIN_FAIL = 'LOGIN_fAIL'
export const  LOGIN_REQUEST = 'LOGIN_REQUEST'
export const  LOG_OUT = 'LOG_OUT'
export const  LOAD_PROFILE = 'LOAD_PROFILE'